### PR TITLE
Bump supported version to 12.0.1

### PR DESCRIPTION
**Pull request by simonbaudart**
Hello,

Umbraco released a new version, here is the bump in config to support the new version with the security update : https://our.umbraco.com/download/releases/1201

Maybe it should be part of a v12 ?

Regards

### CODE REVIEW

**Comment by enkelmedia** [comment]
Thanks man!

I’ll try to get this released asap. I think I need to find a way to support any 12.x version so avoid having to release new versions.

Did you have issues running the current version with 12.0.1?

**Comment by enkelmedia** [comment]
Just looked at this and there seems to be a way to allow wildcards which is probably what we want.

I will investigate a little more and create a new branch/release for Umbraco 12 in the upcoming days.

Ref: https://github.com/NuGet/Home/issues/6376

**Comment by simonbaudart** [comment]
> Thanks man!
> 
> I’ll try to get this released asap. I think I need to find a way to support any 12.x version so avoid having to release new versions.
> 
> Did you have issues running the current version with 12.0.1?

I didn't had the time to deep test with Umbraco 12.0.1, to many installation to update because of the CVE (we decided to go with 11.4.2 instead of going to 12.x)
I can test further but this will be after my holidays (back on 31th july)

Yes, wildcard can help to ensure minor updates can be used with your package.

And : thanks for your work :)

**Comment by enkelmedia** [comment]
Hi again!

I went a head and included your changes in the v12 branch and released a new version: 

https://www.nuget.org/packages/UmbracoSeoVisualizer/12.0.0

Thanks a lot!

/ m

**Comment by simonbaudart** [comment]
Hello ! Thank you for the update, we created our new umbraco image with your package and it seems to works well in Umbraco 12.

**Pull request closed without merging**
